version: '3'
services:
  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - ./cassandra_data:/var/lib/cassandra
    restart: always